[build]
  # Comando per costruire il sito con Vite
  command = "npm run build"
  # Pubblica dalla cartella dist generata da Vite
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"