[build]
  # Nessun comando di build necessario per sito statico
  command = "echo 'No build needed for static site'"
  # Pubblica dalla root del progetto
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"