backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line tells the CMS where the admin folder is
site_url: https://resilient-nougat-34eb70.netlify.app

# Publish mode - simple mode publishes directly
# publish_mode: editorial_workflow

# Media files storage
media_folder: "img/uploads" # Media files will be stored here
public_folder: "/img/uploads" # Public path for media files

# Collections - define the content types
collections:
  - name: "projects" # Used in routes
    label: "Progetti" # Used in the UI
    folder: "_projects" # Where the documents are stored
    create: true # Allow users to create new documents
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "select", options: ["Digital", "Brand", "Web", "Print"]}
      - {label: "Immagine di copertina", name: "thumbnail", widget: "image"}
      - {label: "Descrizione breve", name: "description", widget: "text"}
      - {label: "Contenuto", name: "body", widget: "markdown"}
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        field: {label: "Immagine", name: "image", widget: "image"}
      - {label: "Cliente", name: "client", widget: "string", required: false}
      - {label: "Anno", name: "year", widget: "string"}
      - {label: "Servizi", name: "services", widget: "list", default: ["Design", "Development"]}
      - {label: "Link esterno", name: "external_link", widget: "string", required: false}
      - {label: "In evidenza", name: "featured", widget: "boolean", default: false}

  - name: "pages"
    label: "Pagine"
    files:
      - label: "Homepage"
        name: "home"
        file: "data/homepage.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Titolo Sinistra (VISUAL)", name: "title_left", widget: "string"}
              - {label: "Titolo Destra (DESIGN)", name: "title_right", widget: "string"}
              - {label: "Nome", name: "name_text", widget: "string"}
              - {label: "Tagline", name: "tagline", widget: "string"}
              - {label: "Tipo Media Centrale", name: "center_media_type", widget: "select", options: ["image", "video"], default: "image"}
              - {label: "Media Centrale (Immagine o Video)", name: "center_media", widget: "file", hint: "Carica un'immagine o un video"}
          
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - {label: "Label", name: "label", widget: "string"}
              - {label: "Testo Principale", name: "main_text", widget: "text"}
              - {label: "Colonna 1", name: "column1", widget: "text"}
              - {label: "Colonna 2", name: "column2", widget: "text"}
          
          - label: "Services Section"
            name: "services"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Descrizione", name: "description", widget: "text"}
              - label: "Lista Servizi"
                name: "list"
                widget: "list"
                fields:
                  - {label: "Nome", name: "name", widget: "string"}
                  - {label: "Descrizione", name: "description", widget: "text"}
                  - {label: "Immagine", name: "image", widget: "image"}
          
          - label: "Portfolio Section"
            name: "portfolio"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "string"}
              - label: "Progetti in Homepage"
                name: "projects"
                widget: "list"
                max: 4
                fields:
                  - {label: "Nome", name: "name", widget: "string"}
                  - {label: "Categoria", name: "category", widget: "string"}
                  - {label: "Immagine Box", name: "box_image", widget: "image"}
                  - {label: "Immagine Background", name: "bg_image", widget: "image"}
          
          - label: "Footer"
            name: "footer"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "text"}
              - {label: "Titolo Form", name: "form_title", widget: "string"}
              - {label: "Placeholder Nome", name: "name_placeholder", widget: "string"}
              - {label: "Placeholder Cognome", name: "surname_placeholder", widget: "string"}
              - {label: "Placeholder Messaggio", name: "message_placeholder", widget: "string"}
              - {label: "Testo Bottone", name: "button_text", widget: "string"}
              - {label: "Email Link", name: "email_link", widget: "string"}
              - {label: "Email Footer", name: "bottom_email", widget: "string"}
              - {label: "Telefono Footer", name: "bottom_phone", widget: "string"}

      - label: "Portfolio Page"
        name: "portfolio"
        file: "data/portfolio-page.json"
        fields:
          - {label: "Titolo principale", name: "main_title", widget: "text", default: "PROGETTI"}
          - label: "Filtri"
            name: "filters"
            widget: "list"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Valore", name: "value", widget: "string"}

  - name: "settings"
    label: "Impostazioni"
    files:
      - label: "Informazioni generali"
        name: "general"
        file: "data/settings.json"
        fields:
          - {label: "Titolo del sito", name: "site_title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "phone", widget: "string"}
          - {label: "Indirizzo", name: "address", widget: "text"}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Behance", name: "behance", widget: "string", required: false}