backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

# This line tells the CMS where the admin folder is
site_url: https://resilient-nougat-34eb70.netlify.app

# Publish mode
publish_mode: editorial_workflow

# Media files storage
media_folder: "img/uploads" # Media files will be stored here
public_folder: "/img/uploads" # Public path for media files

# Collections - define the content types
collections:
  - name: "projects" # Used in routes
    label: "Progetti" # Used in the UI
    folder: "_projects" # Where the documents are stored
    create: true # Allow users to create new documents
    slug: "{{slug}}" # Filename template
    fields: # The fields for each document
      - {label: "Titolo", name: "title", widget: "string"}
      - {label: "Data", name: "date", widget: "datetime"}
      - {label: "Categoria", name: "category", widget: "select", options: ["Digital", "Brand", "Web", "Print"]}
      - {label: "Immagine di copertina", name: "thumbnail", widget: "image"}
      - {label: "Descrizione breve", name: "description", widget: "text"}
      - {label: "Contenuto", name: "body", widget: "markdown"}
      - label: "Galleria"
        name: "gallery"
        widget: "list"
        field: {label: "Immagine", name: "image", widget: "image"}
      - {label: "Cliente", name: "client", widget: "string", required: false}
      - {label: "Anno", name: "year", widget: "string"}
      - {label: "Servizi", name: "services", widget: "list", default: ["Design", "Development"]}
      - {label: "Link esterno", name: "external_link", widget: "string", required: false}
      - {label: "In evidenza", name: "featured", widget: "boolean", default: false}

  - name: "pages"
    label: "Pagine"
    files:
      - label: "Homepage"
        name: "home"
        file: "_data/homepage.json"
        fields:
          - label: "Hero Section"
            name: "hero"
            widget: "object"
            fields:
              - {label: "Titolo principale", name: "title", widget: "text", default: "CREO\nESPERIENZE\nDIGITALI\nCOINVOLGENTI"}
              - {label: "Località", name: "location", widget: "string", default: "Caserta, IT"}
              - {label: "CTA Text", name: "cta_text", widget: "text", default: "SCOPRI\nI MIEI\nLAVORI"}
              - {label: "Foto profilo", name: "profile_image", widget: "image"}
          
          - label: "About Section"
            name: "about"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "text", default: "IL MIO\nFOCUS"}
              - {label: "Sottotitolo", name: "subtitle", widget: "string"}
              - {label: "Descrizione 1", name: "description1", widget: "text"}
              - {label: "Descrizione 2", name: "description2", widget: "text"}
          
          - label: "Servizi"
            name: "services"
            widget: "list"
            fields:
              - {label: "Numero", name: "number", widget: "string"}
              - {label: "Titolo", name: "title", widget: "string"}
              - {label: "Descrizione", name: "description", widget: "text"}
          
          - label: "Contact Section"
            name: "contact"
            widget: "object"
            fields:
              - {label: "Titolo", name: "title", widget: "text", default: "INIZIAMO\nQUALCOSA\nDI GRANDE"}
              - {label: "Sottotitolo", name: "subtitle", widget: "string"}
              - {label: "Email", name: "email", widget: "string"}

      - label: "Portfolio Page"
        name: "portfolio"
        file: "_data/portfolio-page.json"
        fields:
          - {label: "Titolo principale", name: "main_title", widget: "text", default: "PROGETTI"}
          - label: "Filtri"
            name: "filters"
            widget: "list"
            fields:
              - {label: "Nome", name: "name", widget: "string"}
              - {label: "Valore", name: "value", widget: "string"}

  - name: "settings"
    label: "Impostazioni"
    files:
      - label: "Informazioni generali"
        name: "general"
        file: "_data/settings.json"
        fields:
          - {label: "Titolo del sito", name: "site_title", widget: "string"}
          - {label: "Email", name: "email", widget: "string"}
          - {label: "Telefono", name: "phone", widget: "string"}
          - {label: "Indirizzo", name: "address", widget: "text"}
          - label: "Social Media"
            name: "social"
            widget: "object"
            fields:
              - {label: "Instagram", name: "instagram", widget: "string", required: false}
              - {label: "LinkedIn", name: "linkedin", widget: "string", required: false}
              - {label: "Behance", name: "behance", widget: "string", required: false}